### ISSUE TITLE
[--restart_dir ./best_model/] PermissionError: [Errno 13] Permission denied: './best_model/'

### ISSUE THREAD

**Issue by Lyueyang2020** [WonhoZhung/DeepICL#1]
Hello, when I use the DeepICL model and follow your tutorial to input
 `[python -u generate.py --ncpu 8 --k 8 --data_dir ../data/data_dir --key_dir ../data/key_dir --restart_dir ./best_model/ --result_dir ../data/result_dir --num_layers 6 --num_dense_layers 3 --num_hidden_feature 128 --num_sample 100 --max_num_add_atom 30 --dist_one_hot_param1 0 10 25 --dist_one_hot_param2 0 15 300 --temperature_factor1 0.1 --temperature_factor2 0.1 --radial_limits 0.9 2.2 --add_noise --pocket_coeff_max 10.0 --pocket_coeff_thr 2.5 --pocket_coeff_beta 0.91 --conditional --use_condition --verbose -y]`,
 the following error occurs:
```
Traceback (most recent call last):
  File "generate.py", line 551, in <module>
    main()
  File "generate.py", line 509, in main
    model = utils.initialize_model(model, args.ngpu > 0, args.restart_dir)
  File "E:\0_deep_learning_program\project\DeepICL\DeepICL\script\utils.py", line 136, in initialize_model
    save_file_dict = torch.load(load_save_file, map_location="cpu")
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: './best_model/'
```
I would greatly appreciate it if you could reply.

**Comment by Lyueyang2020** [comment]
When I use the data processing preprocessing.py script, there are 5316 proteins in the refined-set data set, but when I run [python preprocessing.py ./pdbbind2020/refined-set/ ./process_data/ 8], a loop error occurs:
```
save_dir: ./process_data/
save_dir: ./process_data/
save_dir: ./process_data/
save_dir: ./process_data/
save_dir: ./process_data/
save_dir: ./process_data/
save_dir: ./process_data/
save_dir: ./process_data/
NUM DATA: 5316
NUM DATA: 5316
NUM DATA: 5316
NUM DATA: 5316
NUM DATA: 5316
NUM DATA: 5316
NUM DATA: 5316
NUM DATA: 5316
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
    exitcode = _main(fd)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 114, in _main
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 114, in _main
    exitcode = _main(fd)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
    prepare(preparation_data)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 225, in prepare
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 225, in prepare
    prepare(preparation_data)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
    run_name="__mp_main__")
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\runpy.py", line 263, in run_path
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\runpy.py", line 263, in run_path
    run_name="__mp_main__")
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
    pkg_name=pkg_name, script_name=fname)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\runpy.py", line 96, in _run_module_code
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\runpy.py", line 96, in _run_module_code
    pkg_name=pkg_name, script_name=fname)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
    mod_name, mod_spec, pkg_name, script_name)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\runpy.py", line 85, in _run_code
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\runpy.py", line 85, in _run_code
    mod_name, mod_spec, pkg_name, script_name)
    exec(code, run_globals)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\runpy.py", line 85, in _run_code
  File "E:\0_deep_learning_program\project\DeepICL\DeepICL\data\preprocessing.py", line 45, in <module>
    exec(code, run_globals)
    exec(code, run_globals)
  File "E:\0_deep_learning_program\project\DeepICL\DeepICL\data\preprocessing.py", line 45, in <module>
  File "E:\0_deep_learning_program\project\DeepICL\DeepICL\data\preprocessing.py", line 45, in <module>
    pool = Pool(int(sys.argv[3]))
    pool = Pool(int(sys.argv[3]))
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\context.py", line 119, in Pool
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\context.py", line 119, in Pool
    pool = Pool(int(sys.argv[3]))
    context=self.get_context())
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\pool.py", line 176, in __init__
    context=self.get_context())
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\context.py", line 119, in Pool
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
    context=self.get_context())
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
    self._repopulate_pool()
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\process.py", line 112, in start
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
    self._popen = self._Popen(self)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\process.py", line 112, in start
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\context.py", line 322, in _Popen
    w.start()
    self._popen = self._Popen(self)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\process.py", line 112, in start
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
    self._popen = self._Popen(self)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    return Popen(process_obj)
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    _check_not_importing_main()
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
    is not going to be frozen to produce an executable.''')
  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    _check_not_importing_main()
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.  File "E:\0_deep_learning_program\miniconda3\envs\DeepICL\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
```
I would greatly appreciate it if you could reply.

**Comment by WonhoZhung** [comment]
Hi @Lyueyang2020, thanks for reaching out and your interest in our work!
I will soon update README to include the details of each parameter.
However, I'm afraid I cannot reproduce the permission error, could you please check the permission of the directory via `ls -la` command?
For second issue, I suppose you are running the job on Windows OS, you may try wrapping the whole code in `preprocessing.py` with `if __name__ == "__main__":`. Since Windows OS does not support `fork` during multiprocessing, `spawn` cannot discriminate between the parent and child process which lead to the recursive calling.

**Comment by Lyueyang2020** [comment]
> Hi @Lyueyang2020, thanks for reaching out and your interest in our work! I will soon update README to include the details of each parameter. However, I'm afraid I cannot reproduce the permission error, could you please check the permission of the directory via command? For second issue, I suppose you are running the job on Windows OS, you may try wrapping the whole code in with . Since Windows OS does not support during multiprocessing, cannot discriminate between the parent and child process which lead to the recursive calling.`ls -la``preprocessing.py``if __name__ == "__main__":``fork``spawn`

Thanks for your response, I'll try again later on linux. Have a nice day!
