### ISSUE TITLE
How to create keyas for my own data or how to preprocess my data 

### ISSUE THREAD

**Issue by Anupam-5** [WonhoZhung/DeepICL#5]
First of all thanks for sharing this package, its a great work.

I want to use this package for my protein. I have installed all the dependancies and tried to do the processing step on pdbbind dataset by running the following command: 

`(DeepICL) cdri@cdri-PowerEdge-R750:/disk1/DeepICL/script$ python preprocessing.py ../v2020-other-PL ../processed  1`

its is giving the following output(snippet of the output) : 

```
9icd
/home/cdri/localcolabfold/colabfold-conda/lib/python3.10/site-packages/Bio/PDB/PDBParser.py:388: PDBConstructionWarning: Ignoring unrecognized record 'TER' at line 2777
  warnings.warn(
Traceback (most recent call last):
  File "/disk1/DeepICL/data/processor.py", line 568, in _processor
    pocket_mol, pocket_str, pocket_fn_2 = self._extract_binding_pocket(
  File "/disk1/DeepICL/data/processor.py", line 455, in _extract_binding_pocket
    fd, path = tempfile.mkstemp(
  File "/home/cdri/localcolabfold/colabfold-conda/lib/python3.10/tempfile.py", line 341, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/cdri/localcolabfold/colabfold-conda/lib/python3.10/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/disk1/DeepICL/data/temp/tmp_poc_ipnebn66.pdb'
```

can you please guide me how to use the package to generate the molecules for my protein of interest.
Thanks in advance

**Comment by wangpp010698** [comment]
try to make dir name temp fold in /disk1/DeepICL/data
